{
 "title": "StarRocks / Shared Data 7",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "DS_GRAFANA_STARROCKS_SHARE_DATA",
    "label": "datasource",
    "query": "prometheus"
   },
   { "name": "cluster_name", "query": { "query": "label_values(up, job)" } },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_name\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_name\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", job=\"$cluster_name\"}"
    }
   },
   { "name": "brpc_port", "label": "brpc_port", "query": "8060" }
  ]
 },
 "panels": [
  {
   "title": "Abort Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "AbortTxn RPC Concurrency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rpc_server_${brpc_port}_starrocks_lake_lake_service_abort_txn_concurrency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "AbortTxn RPC QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rpc_server_${brpc_port}_starrocks_lake_lake_service_abort_txn_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Publish Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Publish Tablet Version Latency / QPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_publish_tablet_version_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_publish_tablet_version_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_publish_tablet_version_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Queued Publish Tablet Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_publish_version_queued_tasks{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get Tablet Metadata",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_get_tablet_metadata_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_get_tablet_metadata_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_get_tablet_metadata_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Put Tablet Metadata",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_put_tablet_metadata_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_put_tablet_metadata_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_put_tablet_metadata_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Get Txn Log",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_get_txn_log_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_get_txn_log_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_get_txn_log_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Put Txn Log",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_put_txn_log_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_put_txn_log_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_put_txn_log_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    }
   ]
  },
  {
   "title": "Metacache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metacache Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lake_metacache_usage{job=\"$cluster_name\"} / lake_metacache_capacity{job=\"$cluster_name\"} * 100",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Delvec Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_delvec_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    },
    {
     "title": "Metadata Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lake_metadata_cache_miss_minute"
      }
     ]
    },
    {
     "title": "Txn Log Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "lake_txn_log_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    },
    {
     "title": "Segment Cache Miss Per Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "lake_segment_cache_miss_minute{job=\"$cluster_name\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vacuum Deletes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lake_vacuum_del_file_latency{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} avg"
      },
      {
       "expr": "lake_vacuum_del_file_latency_99{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} p99"
      },
      {
       "expr": "lake_vacuum_del_file_qps{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} qps"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "lake_vacuum_del_file_fails{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} fails"
      }
     ]
    }
   ]
  },
  {
   "title": "Loading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "starrocks_be_async_delta_writer_queue_count{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} async_delta_writer_qsize"
      },
      {
       "expr": "starrocks_be_memtable_flush_queue_count{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} memtable_flush_qsize"
      },
      {
       "expr": "starrocks_be_segment_flush_queue_count{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} segment_flush_qsize"
      },
      {
       "expr": "starrocks_be_update_apply_queue_count{job=\"$cluster_name\"}",
       "legendFormat": "{{instance}} update_apply_qsize"
      }
     ]
    }
   ]
  },
  { "title": "Warm Up", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Warm Up Success Count/Fail count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lake_warmup_tablet_success_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} success"
    },
    {
     "expr": "lake_warmup_tablet_fail_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}} fail"
    }
   ]
  },
  {
   "title": "Warm Up Current Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "lake_warmup_tablet_processing_count{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Warm Up Read Remote Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "lake_warmup_read_remote_bytes_minute{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Warm Up Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lake_warmup_tablet_latency{job=\"$cluster_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}